routes:
  - name: Google Tag Services
    route: www.googletagservices.com/tag/*

  - name: ActiveCampaign
    route: trackcmp.net/visit

  - name: MarkMonitor
    route: beacon.krxd.net/*

  - name: Gigya
    route: cdns.gigya.com/js/gigya.js
    file: gigya.js

  - name: Google Tag Manager
    route: www.googletagmanager.com/gtm.js
    file: gtm.js

  - name: Zopim Chat
    route: "*.zopim.com/"
    file: zopim.js

  - name: Tealium
    route: tags.tiqcdn.com/utag/*
    file: utag.js

  - name: Visual Web Optimizer
    route: dev.visualwebsiteoptimizer.com/j.php
    file: vwo.js

  - name: Optimizely
    route: cdn.optimizely.com/js/*
    file: optimizely.js

  - name: Scorecard Research
    route: sb.scorecardresearch.com/*

  - name: Chartbeat
    route: static.chartbeat.com/js/*

  - name: YieldPro/Ancora
    routes:
      - adserving.ancoraplatform.com/*
      - creatives.ancoraplatform.com/*

  - name: JWPlayer
    route: jwpltx.com/*

  - name: Marktplaats
    route: p.marktplaats.net/*

  - name: Google Adsense
    route: www.google.com/adsense/*
    file: adsense.js

  - name: Google Audiences
    route: www.google.com/ads/ga-audiences

  - name: Google Analytics
    route: www.google-analytics.com/analytics.js
    file: analytics.js

  - name: Google Analytics Plugins
    route: www.google-analytics.com/plugins/*

  - name: Google Analytics Measurements
    route: www.google-analytics.com/collect

  - name: DoubleClick
    route: stats.g.doubleclick.net/r/collect

  - name: YouTube Event Logger
    routes:
      - www.youtube.com/youtubei/v1/log_event
      - www.youtube.com/youtubei/v1/log_interaction
    file: youtube-log-event.json

  - name: NewRelic
    route: js-agent.newrelic.com/*
