window.$zopim = function() {};
window.$zopim.livechat = {
    addTags: function() {},
    appendNotes: function() {},
    badge: { init: function() {}, setLayout: function() {}, setImage: function() {} },
    bubble: { init: function() {}, show: function() {}, hide: function() {} },
    button: { init: function() {}, hide: function() {}, show: function() {} },
    clearAll: function() {},
    concierge: { init: function() {}, setAvatar: function() {}, setName: function() {} },
    cookieLaw: { init: function() {}, comply: function() {}, setDefaultImplicitConsent: function() {} },
    debug: { init: function() {}, connection: function() {}, livechat: function() {} },
    departments: { init: function() {}, filter: function() {}, setVisitorDepartment: function() {} },
    endChat: function() {},
    fire: function() {},
    freeze: function() {},
    generateDeprecatedFunction: function() {},
    generateLimitedFunction: function() {},
    getEmail: function() {},
    getName: function() {},
    getPhone: function() {},
    handleInitError: function() {},
    hideAll: function() {},
    init: function() {},
    isChatting: function() {},
    mobileNotifications: { setDisabled: function() {}, setIgnoreChatButtonVisibility: function() {} },
    offlineForm: { init: function() {}, setGreetings: function() {} },
    prechatForm: { init: function() {}, setGreetings: function() {} },
    removeTags: function() {},
    say: function() {},
    sendVisitorPath: function() {},
    set: function() {},
    setDisableSound: function() {},
    setEmail: function() {},
    setGreetings: function() {},
    setLanguage: function() {},
    setName: function() {},
    setNotes: function() {},
    setOnChatEnd: function() {},
    setOnChatStart: function() {},
    setOnConnected: function() {},
    setOnFlashReady: function() {},
    setOnGreeting: function() {},
    setOnStatus: function() {},
    setOnUnreadMsgs: function() {},
    setPhone: function() {},
    setStatus: function() {},
    theme: { init: function() {}, setTheme: function() {}, setColor: function() {} },
    unreadflag: { disable: function() {}, enable: function() {} },
    window: { init: function() {}, onShow: function() {}, onHide: function() {} }
};